# This file was auto-generated by Fern from our API Definition.

import typing

import httpx

from .http_client import AsyncHttpClient, HttpClient


class BaseClientWrapper:
    def __init__(
        self,
        *,
        header_key: typing.Optional[str] = None,
        api_key: typing.Optional[typing.Union[str, typing.Callable[[], str]]] = None,
        api_token: typing.Optional[typing.Union[str, typing.Callable[[], str]]] = None,
        base_url: str,
        timeout: typing.Optional[float] = None
    ):
        self._header_key = header_key
        self._api_key = api_key
        self._api_token = api_token
        self._base_url = base_url
        self._timeout = timeout

    def get_headers(self) -> typing.Dict[str, str]:
        headers: typing.Dict[str, str] = {
            "X-Fern-Language": "Python",
            "X-Fern-SDK-Name": "fluidstack",
            "X-Fern-SDK-Version": "0.0.1",
        }
        api_key = self._get_api_key()
        api_token = self._get_api_token()
        if api_key is not None and api_token is not None:
            headers["Authorization"] = httpx.BasicAuth(api_key, api_token)._auth_header
        if self._header_key is not None:
            headers["api-key"] = self._header_key
        return headers

    def _get_api_key(self) -> typing.Optional[str]:
        if isinstance(self._api_key, str) or self._api_key is None:
            return self._api_key
        else:
            return self._api_key()

    def _get_api_token(self) -> typing.Optional[str]:
        if isinstance(self._api_token, str) or self._api_token is None:
            return self._api_token
        else:
            return self._api_token()

    def get_base_url(self) -> str:
        return self._base_url

    def get_timeout(self) -> typing.Optional[float]:
        return self._timeout


class SyncClientWrapper(BaseClientWrapper):
    def __init__(
        self,
        *,
        header_key: typing.Optional[str] = None,
        api_key: typing.Optional[typing.Union[str, typing.Callable[[], str]]] = None,
        api_token: typing.Optional[typing.Union[str, typing.Callable[[], str]]] = None,
        base_url: str,
        timeout: typing.Optional[float] = None,
        httpx_client: httpx.Client
    ):
        super().__init__(
            header_key=header_key, api_key=api_key, api_token=api_token, base_url=base_url, timeout=timeout
        )
        self.httpx_client = HttpClient(httpx_client=httpx_client)


class AsyncClientWrapper(BaseClientWrapper):
    def __init__(
        self,
        *,
        header_key: typing.Optional[str] = None,
        api_key: typing.Optional[typing.Union[str, typing.Callable[[], str]]] = None,
        api_token: typing.Optional[typing.Union[str, typing.Callable[[], str]]] = None,
        base_url: str,
        timeout: typing.Optional[float] = None,
        httpx_client: httpx.AsyncClient
    ):
        super().__init__(
            header_key=header_key, api_key=api_key, api_token=api_token, base_url=base_url, timeout=timeout
        )
        self.httpx_client = AsyncHttpClient(httpx_client=httpx_client)
